baseURL: https://chengchenxulbs.netlify.app/
languageCode: en-us
title: Portfolio website for Cissie(Chengchen) Xu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
    subtitle: |-
      A Chinese girl's life experience 
      in London Business School.
    title: Hi, my name is Cissie(Chengchen) Xu
  blog: {}
  contact:
    address:
      - city: City, ST 00000
        country: Country
        street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: xu_chengchen@hotmail.com
        title: Email
    enable: yes
    phone:
      - phone: (075) 1233-2342
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: MFA of London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
  #    - icon: fa-twitter
  #      label: Twitter
  #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100039852075154
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/elenaxu57/
      - icon: fa-github
        label: GitHub
        url: https://github.com/cecexu21
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/chengchen-xu
  image: ''
  name: Chengchen Xu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: 
    title: Cissie Xu'w website
  tiles:
    enable: yes
    showcase:
      - image: my photo.jpg
        subtitle: My previous experience
        title: SELF-INTRODUCTION
        url: blogs/self_introduction
      - image: election.jpg
        subtitle: Who will be the next chancellor?
        title: GERMAN ELECTION POLL TRACKER
        url: blogs/German_election_result
      - image: bikes.jpg
        subtitle: Do you know the rental circumstance of bikes in UK?
        title: EXCESS RENTALS IN TFL BIKE SHARING
        url: blogs/BikesTFL
      - image: cpi.jpg
        subtitle: How has the CPI and its components changed over the last few years?
        title: SECRETS IN CPI 
        url: blogs/cpi_changes
      - image: gdp.jpg
        subtitle: How are GDP component changing among countries?
        title: GDP:An Economy’s All
        url: blogs/GDP_components
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hope to have chances to connect with you and hear more about your stories.
      \n   Thanks for your visit to my website! \n    Now, here is getting close to the end of my presentation.
       \n   To explore more about me, you can click on the icons below, welcome to be my friends on these social platforms."
    title: That is the end
    url: blogs
